import scrapy


class FundRankingItem(scrapy.Item):
    fund_code = scrapy.Field()
    fund_name = scrapy.Field()
    pinyin_abbr = scrapy.Field()
    nav_date = scrapy.Field()
    unit_nav = scrapy.Field()
    accumulated_nav = scrapy.Field()
    daily_growth_rate = scrapy.Field()
    week_1_rate = scrapy.Field()
    month_1_rate = scrapy.Field()
    month_3_rate = scrapy.Field()
    month_6_rate = scrapy.Field()
    year_1_rate = scrapy.Field()
    year_2_rate = scrapy.Field()
    year_3_rate = scrapy.Field()
    ytd_rate = scrapy.Field()
    since_inception_rate = scrapy.Field()
    establish_date = scrapy.Field()
    purchase_status = scrapy.Field()
    interval_growth_rate = scrapy.Field()
    original_fee = scrapy.Field()
    fee_rate = scrapy.Field()
    discount = scrapy.Field()
    discounted_fee = scrapy.Field()
    query_start_date = scrapy.Field()
    query_end_date = scrapy.Field()
    sort_column = scrapy.Field()
    page_index = scrapy.Field()


class FundHoldingItem(scrapy.Item):
    fund_code = scrapy.Field()
    report_date = scrapy.Field()
    report_year = scrapy.Field()
    report_quarter = scrapy.Field()
    stock_code = scrapy.Field()
    stock_name = scrapy.Field()
    rank_num = scrapy.Field()
    nav_ratio = scrapy.Field()
    share_count = scrapy.Field()
    market_value = scrapy.Field()
    holding_type = scrapy.Field()
